# For more information: https://laravel.com/docs/sail
version: '3.5'
services:
    robokar:
        build:
            context: src
            dockerfile: ./docker-files/Dockerfile
            args:
                WWWGROUP: 'www-data'
        ports:
            - "80:80"
        container_name: robokar
        environment:
            WWWUSER: 'www-data'
        volumes:
            - './src:/var/www/html'
        networks:
            robocar_network:
                ipv4_address: 172.1.0.2
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql:8.0'
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: robocar
        volumes:
            - './mysql-data:/var/lib/mysql'
        networks:
            robocar_network:
                ipv4_address: 172.1.0.3
networks:
    robocar_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.0.0/24
